name: Feature request
description: Suggest a new feature to add to Sopwith.
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a feature request.
  - type: textarea
    id: description
    attributes:
      label: What's your idea?
      description: >
        Make sure to take a look at the [project philosophy](../PHILOSOPHY.md)
        so you understand what features are in scope for this project.
    validations:
      required: true
